export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const ADD_POKEMON_DATA = 'ADD_POKEMON_DATA';
export const ADD_POKEMONS = 'ADD_POKEMONS';
export const ADD_POKEMON_TYPES= 'ADD_POKEMON_TYPES';

export const SET_POKEMON_TYPE_TERM = 'SET_POKEMON_TYPE_TERM';
export const SET_VIEW = 'SET_VIEW';
export const CLEAR_PAGE = 'CLEAR_PAGE';
